{
 "title": "Network Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Devices", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Thoughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$Devices\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$Devices\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {}
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "BGP Peer Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "UP Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "History Total BGP Prefixes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_prefixes{network_instance_name=\"default\", source=\"$Devices\"}",
     "legendFormat": "History Total BGP Prefixes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$Devices\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"$Devices\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "platform_control_memory_reserved{source=\"$Devices\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$Devices\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "platform_control_memory_physical{source=\"$Devices\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"$Devices\", interface_name=~\"e1-[1-3]\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}