connection_options:
  pygnmi:
    port: 57400
    timeout: 10
    insecure: true
    ssl: false
    username: admin
    password: NokiaSrl1!

  gnmic:
    port: 57400
    timeout: 10
    insecure: true
    ssl: false
    username: admin
    password: NokiaSrl1!

  netmiko:
    extras:
      device_type: nokia_srl
    username: admin
    password: NokiaSrl1!
#platform: srl



